package dev.kausik.shaders.geometry;

import dev.kausik.shaders.runtime.ShaderRuntime;
import java.util.ArrayList;
import java.util.Collection;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.ToIntFunction;
import net.minecraft.client.renderer.blockentity.state.BlockEntityRenderState;
import net.minecraft.client.renderer.entity.state.EntityRenderState;
import net.minecraft.client.renderer.feature.BlockModelFeatureRenderer;
import net.minecraft.client.renderer.feature.ItemFeatureRenderer;
import net.minecraft.client.renderer.feature.ModelFeatureRenderer;
import net.minecraft.client.renderer.feature.submit.SubmitNode;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.level.block.state.BlockState;

/** Carries real material identity through deferred feature preparation and both draw replays. */
public final class FeatureDrawContext {
  public enum Kind {
    NONE,
    ENTITY,
    BLOCK_ENTITY
  }

  public record DrawTag(
      Kind kind,
      int entityId,
      int blockEntityId,
      float red,
      float green,
      float blue,
      float alpha,
      boolean shadowOnly) {
    public DrawTag withOverlay(int overlay) {
      int x = overlay & 0xffff;
      int y = overlay >>> 16;
      // These are the actual texels generated by Minecraft's OverlayTexture. The pack uses
      // blend amount, whereas the texture stores the amount of the original color to retain.
      if (y < 8)
        return new DrawTag(kind, entityId, blockEntityId, 1, 0, 0, 77 / 255.0f, shadowOnly);
      if (x == 0)
        return alpha == 0
            ? this
            : new DrawTag(kind, entityId, blockEntityId, 0, 0, 0, 0, shadowOnly);
      int retained = (int) ((1 - Math.clamp(x, 0, 15) / 15.0f * .75f) * 255);
      return new DrawTag(kind, entityId, blockEntityId, 1, 1, 1, 1 - retained / 255.0f, shadowOnly);
    }
  }

  public static final DrawTag NONE = new DrawTag(Kind.NONE, -1, -1, 0, 0, 0, 0, false);
  private static final Map<Object, DrawTag> stateTags = new IdentityHashMap<>();
  private static final Map<SubmitNode, DrawTag> submitTags = new IdentityHashMap<>();
  private static ToIntFunction<EntityType<?>> entities;
  private static ToIntFunction<BlockState> blocks;
  private static DrawTag submission = NONE;
  private static DrawTag drawing = NONE;

  private FeatureDrawContext() {}

  /** Install alongside the immutable terrain material resolver, before entering a world. */
  public static void configure(
      ToIntFunction<EntityType<?>> entityIds, ToIntFunction<BlockState> blockIds) {
    entities = Objects.requireNonNull(entityIds);
    blocks = Objects.requireNonNull(blockIds);
  }

  public static void beginExtraction() {
    stateTags.clear();
    submitTags.clear();
    submission = NONE;
    drawing = NONE;
  }

  public static void extractedBlockEntity(BlockEntityRenderState state, BlockState block) {
    if (state != null && blocks != null) {
      stateTags.put(
          state, new DrawTag(Kind.BLOCK_ENTITY, -1, blocks.applyAsInt(block), 0, 0, 0, 0, false));
    }
  }

  public static void shadowOnlyEntity(EntityRenderState state) {
    DrawTag tag = entityTag(state);
    stateTags.put(state, new DrawTag(tag.kind, tag.entityId, tag.blockEntityId, 0, 0, 0, 0, true));
  }

  public static DrawTag entityTag(EntityRenderState state) {
    DrawTag cached = stateTags.get(state);
    if (cached != null) return cached;
    return entities == null
        ? NONE
        : new DrawTag(Kind.ENTITY, entities.applyAsInt(state.entityType), -1, 0, 0, 0, 0, false);
  }

  public static DrawTag blockEntityTag(BlockEntityRenderState state) {
    DrawTag tag = stateTags.get(state);
    if (tag == null && blocks != null && ShaderRuntime.isRendering()) {
      throw new IllegalStateException("Block entity submission has no extracted material state");
    }
    return tag == null ? NONE : tag;
  }

  public static DrawTag setSubmission(DrawTag tag) {
    DrawTag previous = submission;
    submission = tag;
    return previous;
  }

  public static void recordSubmit(SubmitNode submit) {
    if (!ShaderRuntime.isRendering()) return;
    DrawTag tag = submission;
    if (tag.kind != Kind.NONE) {
      if (submit instanceof ModelFeatureRenderer.Submit<?> model)
        tag = tag.withOverlay(model.overlayCoords());
      else if (submit instanceof ItemFeatureRenderer.Submit item)
        tag = tag.withOverlay(item.overlayCoords());
      else if (submit instanceof BlockModelFeatureRenderer.Submit block)
        tag = tag.withOverlay(block.overlayCoords());
    }
    record(submit, tag);
  }

  static void record(SubmitNode submit, DrawTag tag) {
    submitTags.put(submit, tag);
  }

  /** Read-only test diagnostics; no counting or allocation is added to the normal draw path. */
  public static Map<DrawTag, Integer> submittedTagCounts() {
    Map<DrawTag, Integer> counts = new LinkedHashMap<>();
    for (DrawTag tag : submitTags.values()) counts.merge(tag, 1, Integer::sum);
    return Map.copyOf(counts);
  }

  public static DrawTag tag(SubmitNode submit) {
    return submitTags.getOrDefault(submit, NONE);
  }

  public static DrawTag currentDrawTag() {
    return drawing;
  }

  public static DrawTag setDrawTag(DrawTag tag) {
    DrawTag previous = drawing;
    drawing = tag;
    return previous;
  }

  public static boolean shouldDraw(DrawTag tag) {
    ShaderRuntime runtime = ShaderRuntime.get();
    if (runtime == null || !ShaderRuntime.isRendering()) return !tag.shadowOnly;
    if (!runtime.isShadow()) return !tag.shadowOnly;
    String property =
        switch (tag.kind) {
          case ENTITY -> tag.shadowOnly ? "shadowPlayer" : "shadowEntities";
          case BLOCK_ENTITY -> "shadowBlockEntities";
          case NONE -> null;
        };
    return property == null || !runtime.programs().properties.get(property, "true").equals("false");
  }

  /**
   * Unordered groups retain batching by equal material/overlay; sorted translucency never moves.
   */
  public static <T extends SubmitNode> List<List<T>> partition(
      Collection<T> submits, boolean strictlyOrdered) {
    if (!strictlyOrdered) {
      Map<DrawTag, List<T>> groups = new LinkedHashMap<>();
      for (T submit : submits)
        groups.computeIfAbsent(tag(submit), ignored -> new ArrayList<>()).add(submit);
      return new ArrayList<>(groups.values());
    }
    List<List<T>> groups = new ArrayList<>();
    DrawTag previous = null;
    List<T> group = null;
    for (T submit : submits) {
      DrawTag tag = tag(submit);
      if (!tag.equals(previous)) {
        group = new ArrayList<>();
        groups.add(group);
      }
      group.add(submit);
      previous = tag;
    }
    return groups;
  }
}
